name: smart_expense_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # OCR & Image
  #google_ml_kit: ^0.20.0
  google_mlkit_text_recognition: ^0.13.0
  image_picker: ^1.1.2
  image: ^4.5.4
  path_provider: ^2.1.5
  exif: ^2.0.0    # For orientation correction

  # Camera
  camera: ^0.11.0+2

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path: ^1.9.0
  
  # Permissions
  permission_handler: ^11.3.1

  # Others
  cupertino_icons: ^1.0.8
  crypto: ^3.0.6
  fl_chart: ^0.68.0
  intl: ^0.19.0
  vector_math: ^2.1.4
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true